spring:
  application:
    name: Microservice-1
    
server:  port: 5555
  
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone : http://localhost:1111/eureka